version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python-packages:
        patterns:
          - "*"
    ignore:
      - dependency-name: "scipy"
        versions: ["1.13.0"]
      - dependency-name: "dash-mantine-components"
