name: Unit Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.4
      - name: Set up python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4.0.2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install project
        run: poetry install --no-interaction --with test
      - name: Run tests
        run: poetry run pytest --cov=src --cov-branch --cov-report=xml
# Commented out because CodeCov still needs to get set up on GitHub
#      - name: Upload coverage
#        uses: codecov/codecov-action@v4.3.1
#        with:
#          file: ./coverage.xml
#          fail_ci_if_error: true
#          token: ${{ secrets.CODECOV_TOKEN }}
